site_name: Virtual Control Plane
repo_url: https://github.com/onmetal/virtual-controlplane/
site_url: https://onmetal.github.io/virtual-controlplane/
edit_uri: edit/main/docs/
theme:
  name: material
  logo: assets/logo.png
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  font:
    text: 'Work Sans'

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - codehilite
  - admonition
  - footnotes
  - abbr
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Usage:
    - Installation: usage/installation.md
    - Helm Repository: usage/helm.md
    - Cert Manager: usage/cert-manager.md
    - Druid: usage/druid.md
    - Etcd: usage/etcd.md
    - Template Operator: usage/template.md
    - Virtual Control Plane: usage/vc.md
    - Access API Server: usage/access.md
  - Developer Guide:
      - Documentation: development/documentation.md
      - Contribution Guide: development/contribution.md
  - OnMetal Documentation ⧉: https://onmetal.github.io/documentation/
  - Presentations:
    - Virtual Control Plane: https://docs.google.com/presentation/d/1oNQMpDpjKyF27EzypQf806ygLtQgDWnitycJ_zTHs0w/edit?usp=sharing
