{
 "title": "Node Details",
 "description": "Details about Shoot worker nodes.",
 "tags": [
  "workload",
  "shoot"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(kube_node_info{type=\"shoot\"}, node)"
    }
   },
   {
    "name": "Condition",
    "query": {
     "query": "label_values(kube_node_status_condition, condition)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "description": "Shows how much percent of the CPU is being used on the node $Node.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\", node=~\"$Node\"}[$__rate_interval])) / sum(kube_node_status_allocatable_cpu_cores{node=~\"$Node\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "description": "Shows how much percent of the memory is being used on the node $Node.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_Active_bytes{node=~\"$Node\"}) / sum(kube_node_status_allocatable_memory_bytes{node=~\"$Node\"}) * 100"
    }
   ]
  },
  {
   "title": "Node CPU Usage ($Node)",
   "type": "graph",
   "description": "Shows a node's CPU usage over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\", node=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"$Node\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"$Node\"}) - sum(rate(node_cpu_seconds_total{mode!=\"idle\", node=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Node Memory Usage ($Node)",
   "type": "graph",
   "description": "Shows a node's memory usage over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_Active_bytes{node=~\"$Node\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$Node\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$Node\"}) - sum(node_memory_Active_bytes{node=~\"$Node\"})",
     "legendFormat": "Unused"
    }
   ]
  },
  {
   "title": "Network I/O pressure ($Node)",
   "type": "graph",
   "description": "Shows the node's network I/O pressure.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\",type=\"shoot\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate(container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\",type=\"shoot\"}[$__rate_interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Node Filesystem Size ($Node)",
   "type": "graph",
   "description": "Shows the size of the node's filesystem, how much space is free and how much space is available to non-root users.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{mountpoint=\"/\",node=~\"$Node\"})",
     "legendFormat": "Size"
    },
    {
     "expr": "sum(node_filesystem_free_bytes{mountpoint=\"/\",node=~\"$Node\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "sum(node_filesystem_avail_bytes{mountpoint=\"/\",node=~\"$Node\"})   ",
     "legendFormat": "Available"
    }
   ]
  },
  { "title": "Condition", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Node $Condition condition",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "repeat": "Condition",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (kube_node_status_condition{node=~\"$Node\",condition=~\"$Condition\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "System Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "System services CPU usage",
   "type": "graph",
   "description": "Shows the CPU usage of all system services running on node $Node.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{systemd_service_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[$__rate_interval])) by (systemd_service_name)",
     "legendFormat": "{{ systemd_service_name }}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{systemd_service_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "System services Memory usage",
   "type": "graph",
   "description": "Shows the Memory usage of all system services running on node $Node.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{systemd_service_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}) by (systemd_service_name)",
     "legendFormat": "{{ systemd_service_name }}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{systemd_service_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Node Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collector Duration",
     "type": "graph",
     "description": "Shows the time it takes for the node exporter to collect data for each collector.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(node_scrape_collector_duration_seconds{node=~\"$Node\"}) by (collector)",
       "legendFormat": "{{ collector }}"
      }
     ]
    }
   ]
  }
 ]
}