---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vc.onmetal.de:system:etcd-druid
  namespace: {{ .Release.Namespace }}
  labels:
    app: virtual-controlplane
    component: etcd-druid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vc.onmetal.de:system:etcd-druid
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount }}
  namespace: {{ .Release.Namespace }}
