{{define "kubeconfig"}}
apiVersion: v1
kind: Config
current-context: {{ .Values.context}}
contexts:
- context:
    cluster: {{ .Values.context}}
    user: {{ .Values.username }}
  name: {{ .Values.context}}
clusters:
- cluster:
    certificate-authority-data: {{ index .Values.tlsSecret.data "ca.crt" }}
    server: {{ .Values.apiService }}
  name: {{ .Values.context}}
users:
- name: {{ .Values.username }}
  user:
    client-certificate-data: {{ index .Values.tlsSecret.data "tls.crt" }}
    client-key-data: {{ index .Values.tlsSecret.data "tls.key" }}
{{end}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Template.metadata.name }}
  namespace: {{ .Template.metadata.namespace }}
type: Opaque
data:
  ca.crt: {{ index .Values.tlsSecret.data "ca.crt" }}
  tls.crt: {{ index .Values.tlsSecret.data "tls.crt" }}
  tls.key: {{ index .Values.tlsSecret.data "tls.key" }}
  kubeconfig: {{ include "kubeconfig" . | b64enc }}