apiVersion: v2
name: virtual-controlplane
description: A Helm chart for a Virtual Kubernetes controlplane
maintainers:
- name: afritzler
sources:
  - https://github.com/onmetal/virtual-controlplane
type: application
version: 0.1.1
appVersion: "1.20.5"