apiVersion: v2
name: kine
description: A Helm chart for Kine
maintainers:
- name: afritzler
sources:
  - https://github.com/onmetal/virtual-controlplane
type: application
version: 0.1.2
appVersion: "0.6.1"
