apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubernetes-ca
spec:
  isCA: true
  commonName: kubernetes
  secretName: kubernetes-ca
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - signing
    - key encipherment
    - server auth
    - client auth
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-apiserver
spec:
  secretName: kube-apiserver-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: kubernetes
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - localhost
    - kube-apiserver
    - kubernetes
    - kubernetes.default
    - kubernetes.default.svc
    - kubernetes.default.svc.cluster
    - kubernetes.default.svc.cluster.local
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    name: kubernetes-ca
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-controller-manager-client
spec:
  secretName: kube-controller-manager-client-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: system:kube-controller-manager
  subject:
    organizations:
      - system:kube-controller-manager
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - server auth
    - client auth
  issuerRef:
    name: kubernetes-ca
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-apiserver-sa
spec:
  secretName: kube-apiserver-sa
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: service-accounts
  subject:
    organizations:
      - Kubernetes
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - server auth
    - client auth
  issuerRef:
    name: kubernetes-ca
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin
spec:
  secretName: admin
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: admin
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048
  subject:
    organizations:
      - system:masters
  usages:
    - server auth
    - client auth
  issuerRef:
    name: kubernetes-ca
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kubernetes-ca
spec:
  ca:
    secretName: kubernetes-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-ca
spec:
  isCA: true
  commonName: etcd
  secretName: etcd-ca
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - signing
    - key encipherment
    - server auth
    - client auth
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-server
spec:
  secretName: etcd-server-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: etcd-server
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - localhost
    - etcd-local
    - etcd-client
  issuerRef:
    name: etcd-ca
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-client
spec:
  secretName: etcd-client-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: etcd-client
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  issuerRef:
    name: etcd-ca
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: etcd-ca
spec:
  ca:
    secretName: etcd-ca