apiVersion: matryoshka.onmetal.de/v1alpha1
kind: Kubeconfig
metadata:
  name: kubeconfig-for-admin
spec:
  clusters:
    - cluster:
        certificateAuthoritySecret:
          name: admin
        server: https://kube-apiserver
      name: default
  contexts:
    - context:
        cluster: default
        user: admin
      name: default
  currentContext: default
  secretName: kubeconfig-for-admin
  users:
    - name: admin
      user:
        clientCertificateSecret:
          name: admin
        clientKeySecret:
          name: admin
