apiVersion: matryoshka.onmetal.de/v1alpha1
kind: Kubeconfig
metadata:
  name: kube-controller-manager-kubeconfig
spec:
  clusters:
    - cluster:
        certificateAuthoritySecret:
          name: kube-controller-manager-client-tls
        server: https://kube-apiserver
      name: default
  contexts:
    - context:
        cluster: default
        user: system:kube-controller-manager
      name: default
  currentContext: default
  secretName: kube-controller-manager-kubeconfig
  users:
    - name: system:kube-controller-manager
      user:
        clientKeySecret:
          name: kube-controller-manager-client-tls
        clientCertificateSecret:
          name: kube-controller-manager-client-tls
