{
 "title": "Kubernetes API Server Details",
 "tags": [
  "seed",
  "controlplane"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "verbs",
    "label": "Verbs",
    "query": "DELETE,PUT,POST,DELETECOLLECTION,WATCH,GET,LIST,PATCH,CONNECT,UPDATE,CREATE"
   },
   { "name": "rate", "label": "Rate", "query": "3m,5m" }
  ]
 },
 "panels": [
  {
   "title": "Overall API Server Request Rates",
   "type": "graph",
   "description": "Shows the rate of all API server requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total[$rate]))",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "API Server Request Latency",
   "type": "graph",
   "description": "Shows the request latency of each verb for the API server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum by(verb) (rate(apiserver_latency_seconds:quantile{verb=~\"$verbs\"}[$rate]) >= 0)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "API Server Request Rates Per Verb",
   "type": "graph",
   "description": "Shows the request rate per verb for the API server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{verb=~\"$verbs\"}[$rate])) by(verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "API Server Request Rates Per Verb (Avg)",
   "type": "graph",
   "description": "Shows the average rate of requests to the API server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(apiserver_request_total{verb=~\"$verbs\"}[$rate])) by (verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "API Server Request Rates Per Scope",
   "type": "graph",
   "description": "Shows the request rate per scope for the API server.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total[$rate])) by(scope)",
     "legendFormat": "{{scope}}-scope"
    }
   ]
  },
  {
   "title": "API Resources",
   "type": "graph",
   "description": "Shows the number of API Resources that are in the cluster.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max(etcd_object_counts) by (resource)) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "API Server Request Rates Per Resource",
   "type": "graph",
   "description": "Shows the request rate per resource for the API server.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total[$rate])) by(resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "API Server Request Rates Per Verb And Resource",
   "type": "graph",
   "description": "Shows the request rate per verb and resource for the API server.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{verb=~\"$verbs\"}[$rate])) by(resource,verb,subresource)",
     "legendFormat": "{{verb}}/{{resource}}/{{subresource}}"
    }
   ]
  },
  { "title": "Dropped Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Dropped Requests",
   "type": "graph",
   "description": "Number of requests/s that are dropped by the API Server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_dropped_requests_total[$rate])) by (requestKind)",
     "legendFormat": "{{ requestKind }}"
    }
   ]
  },
  {
   "title": "Inflight Requests",
   "type": "graph",
   "description": "Current number of inflight requests/s in the API Server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_current_inflight_requests[$rate])) by (requestKind)",
     "legendFormat": "{{ requestKind }}"
    }
   ]
  },
  {
   "title": "Request Terminations",
   "type": "graph",
   "description": "Number of requests/s that are terminated by the API Server. Includes response code, scope and verb.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_terminations_total{verb=~\"$verbs\"}[$rate])) by (code, scope, verb)",
     "legendFormat": "{{ code }} {{ scope }} {{ verb }} "
    }
   ]
  }
 ]
}