apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kube-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: virtual-controlplane
      component: kube-apiserver
