apiVersion: v1
kind: Secret
metadata:
  name: kube-apiserver-ca
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ca.crt: {{ .Values.tls.kubeAPIServer.ca.crt | b64enc }}
  ca.key: {{ .Values.tls.kubeAPIServer.ca.key | b64enc }}
