apiVersion: v1
kind: Secret
metadata:
  name: kube-apiserver
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  ca.crt: {{ .Values.tls.kubeAPIServer.ca.crt | b64enc }}
  tls.crt: {{ .Values.tls.kubeAPIServer.server.crt | b64enc }}
  tls.key: {{ .Values.tls.kubeAPIServer.server.key | b64enc }}
