apiVersion: v1
kind: Secret
metadata:
  name: kube-apiserver-basic-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  basic_auth.csv: {{ printf "%s,admin,admin,system:masters" .Values.apiServer.tls.basicAuthPassword | b64enc }}
