apiVersion: v1
kind: Secret
metadata:
  name: kube-apiserver-static-token
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  static_tokens.csv: {{ printf "%s,admin,admin,system:masters" .Values.apiServer.tls.staticToken | b64enc }}
