apiVersion: v1
kind: Secret
metadata:
  name: kubeconfig-for-admin
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ca.crt: {{ .Values.tls.kubeAPIServer.ca.crt | b64enc }}
  tls.crt: {{ .Values.tls.admin.crt | b64enc }}
  tls.key: {{ .Values.tls.admin.key | b64enc }}
  kubeconfig: {{ include "garden.kubeconfig-admin" . | b64enc }}
