apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  name: virtual-controlplane-ingress
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.apiServer.externalDNSName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.apiServer.serviceName }}
            port:
              number: 443
{{- if .Values.ingress.useTLS }}
  tls:
  - secretName: virtual-controlplane-tls
    hosts:
    - .Values.apiServer.externalDNSName
{{- end }}
