apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiServer.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: virtual-controlplane
    component: kube-apiserver
spec:
  type: ClusterIP
  selector:
    app: virtual-controlplane
    component: kube-apiserver
  ports:
  - name: kube-apiserver
    protocol: TCP
    port: 443
    targetPort: 443
