apiVersion: template.onmetal.de/v1alpha1
kind: Template
metadata:
  name: kubeconfig-for-admin
  namespace: {{ .Release.Namespace }}
spec:
  groupKinds:
    - group: ""
      kind: Secret
  commonLabels:
    managed-by: kubeconfig-for-admin
  selector:
    matchLabels:
      managed-by: kubeconfig-for-admin
  prune: true
  sources:
  - name: tlsSecret
    object:
      apiVersion: v1
      kind: Secret
      name: {{ .Values.admin.tls.secretName }}
  - name: username
    value: {{ .Values.admin.username }}
  - name: apiService
    value: https://{{ .Values.apiServer.externalDNSName}}
  - name: context
    value: {{ .Values.admin.contextName }}
  data:
    configMapRef:
      name: kubeconfig-template
