apiVersion: template.onmetal.de/v1alpha1
kind: Template
metadata:
  name: kube-controller-manager-kubeconfig
  namespace: {{ .Release.Namespace }}
spec:
  groupKinds:
    - group: ""
      kind: Secret
  commonLabels:
    managed-by: kube-controller-manager-kubeconfig
  selector:
    matchLabels:
      managed-by: kube-controller-manager-kubeconfig
  prune: true
  sources:
  - name: tlsSecret
    object:
      apiVersion: v1
      kind: Secret
      name: {{ .Values.controllerManager.tls.secretName }}
  - name: username
    value: {{ .Values.controllerManager.username }}
  - name: apiService
    value: {{ .Values.apiServer.serviceURL}}
  - name: context
    value: {{ .Values.controllerManager.contextName }}
  data:
    configMapRef:
      name: kubeconfig-template
