name: Deploy gh-pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: install mkdocs-material & deps
        run: |
          pip install -r .github/requirements.txt
      - name: install mkdocs plugins
        run: |
          pip install -r docs/requirements.txt
          mkdocs build
      - name: deploy
        if: ${{ github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./site 
